## **Data Preparation**
#### *@authors: Jyontika Kapoor, Josie Ramírez, Miraya Gupta*
This notebook contains our preparation for the data analysis process using the provided Kaggle dataset by Eni.


**Table of Contents**
1. [Exploratory Data Analysis (EDA)](#sec1)
2. [Splitting Data into Pairs](#sec2)
3. [Jyontika's Section](#sec3)
4. [Miraya's Section](#sec4)
5. [Audrey's Section](#sec5)

In [2]:
import pandas as pd

#### 1. Exploratory Data Analysis (EDA) <a class="anchor" id="sec1"></a>

In [2]:
df = pd.read_csv('TikTok-Prep-Data.csv')
print(df.head)

<bound method NDFrame.head of                                       authorMeta/avatar  authorMeta/digg  \
0     https://p16-sign-sg.tiktokcdn.com/aweme/720x72...              420
1     https://p16-sign-va.tiktokcdn.com/tos-maliva-a...            10800
2     https://p16-sign-va.tiktokcdn.com/tos-maliva-a...              251
3     https://p16-sign-va.tiktokcdn.com/tos-maliva-a...              218
4     https://p19-sign.tiktokcdn-us.com/tos-useast5-...            47600
...                                                 ...              ...
1195  https://p16-sign-va.tiktokcdn.com/musically-ma...               38
1196  https://p16-sign-sg.tiktokcdn.com/aweme/720x72...            12900
1197  https://p16-sign-va.tiktokcdn.com/tos-maliva-a...           195200
1198  https://p16-sign-sg.tiktokcdn.com/aweme/720x72...            12900
1199  https://p16-sign-va.tiktokcdn.com/musically-ma...            27900

      authorMeta/fans  authorMeta/following  authorMeta/heart  \
0            13200000                    28         150400000
1             1300000                   182          35100000
2              696800                    42          15900000
3              510200                    56          32100000
4             3300000                   690         137300000
...               ...                   ...               ...
1195           251100                     0           2600000
1196         21400000                    39         641900000
1197            44000                  1336           2900000
1198         21400000                    39         641900000
1199          6100000                   422          51500000

            authorMeta/id         authorMeta/name authorMeta/nickName  \
0     6713126981665686530                miso_ara       미소아라 Miso_Ara
1     6929583089811522566                crinka11        Chris Rinker
2     7083448802635596842             iampets_com             IamPéts
3     7087287470497645573        dailydosevideos_     dailydosevideos
4     6621521206107717638               jakeypoov        Jake Sherman
...                   ...                     ...                 ...
1195  6764660438212592646  tiktok.dance.tuttorial  dance tutorials ✌️
1196  6558418321485414402          cutybeautykhan         Beauty khan
1197  6687361564112733189               julespods               jules
1198  6558418321485414402          cutybeautykhan         Beauty khan
1199  6806465339817673733          thejohnnydshow    John Di Domenico

                                   authorMeta/signature  authorMeta/verified  \
0               soonent@soon-ent.co.kr\n.\n Miso Ara IG                 True
1                                  insta: chrisrinker73                False
2     Pet supplies, toys online store. All products ...                False
3     Daily dose of videos/memes \nsupport the page ...                False
4     -.-- --- ..- .-. .     .-.. --- ...- . -..    ...                 True
...                                                 ...                  ...
1195                                 MMTHANKYOU\nscorDN                False
1196                                                 Hi                 True
1197                                        hello there                False
1198                                                 Hi                 True
1199  John Di Domenico \nEmmy Nominated, Award Winni...                 True

      ...                                  musicMeta/playUrl  playCount  \
0     ...  https://sf16-ies-music-sg.tiktokcdn.com/obj/ti...  200600000
1     ...  https://sf16-ies-music-va.tiktokcdn.com/obj/mu...   79600000
2     ...  https://sf16-ies-music-va.tiktokcdn.com/obj/ie...  106100000
3     ...  https://sf16-ies-music-va.tiktokcdn.com/obj/mu...   72500000
4     ...  https://sf16-ies-music-va.tiktokcdn.com/obj/mu...   62700000
...   ...                                                ...        ...
1195  ...  https://sf16-ies-music-va.tiktokcdn.com/obj/mu...   16700000
1196  ...  https://sf16-ies-music-va.tiktokcdn.com/obj/mu...   35600000
1197  ...  https://sf16-ies-music-va.tiktokcdn.com/obj/mu...    8600000
1198  ...                                                NaN   27400000
1199  ...  https://sf16-ies-music-va.tiktokcdn.com/obj/to...   28500000

      searchHashtag/name searchHashtag/views  shareCount  \
0                   meme                556B      377700
1                   meme                556B      205400
2                   meme                556B      323000
3                   meme                556B      133400
4                   meme                556B      252900
...                  ...                 ...         ...
1195         tiktokdance               17.2B      198000
1196         tiktokdance               17.2B       17200
1197         tiktokdance               17.2B       53000
1198         tiktokdance               17.2B       10400
1199         tiktokdance               17.2B       48500

                                                   text  videoMeta/duration  \
0     Ara Woah  #woah  #woahchallenge  #foryou  #fyp...                  17
1                         #fyp #meme #funny #meme #vine                  11
2     The end #funny #funnyvideos #animals #haha #me...                  25
3     Try not to laugh  hard #meme #trynottolaughtik...                  62
4     HE DIDN’T HAVE HIS MASK ON  @abbysherm (Follow...                  36
...                                                 ...                 ...
1195  tutorial on how to do “american boy” #foryoupa...                  27
1196  #tiktokcomedy #cutebeuty #tiktokdance @__angel...                  12
1197  what our pep assemblies are like  #fyp #foryou...                  48
1198  #tiktokindia #cutebeuty #tiktokdance @__angel_...                  14
1199  #go #gogogo #whosnext #trump #trump2020 #tikto...                  10

     videoMeta/height  videoMeta/width  \
0                1280              720
1                1024              576
2                1024              576
3                1024              576
4                1024              576
...               ...              ...
1195              960              540
1196             1024              576
1197             1280              720
1198             1024              576
1199             1024              576

                                            webVideoUrl
0     https://www.tiktok.com/@miso_ara/video/6797294...
1     https://www.tiktok.com/@crinka11/video/6958603...
2     https://www.tiktok.com/@iampets_com/video/7083...
3     https://www.tiktok.com/@dailydosevideos_/video...
4     https://www.tiktok.com/@jakeypoov/video/681538...
...                                                 ...
1195  https://www.tiktok.com/@tiktok.dance.tuttorial...
1196  https://www.tiktok.com/@cutybeautykhan/video/6...
1197  https://www.tiktok.com/@julespods/video/680097...
1198  https://www.tiktok.com/@cutybeautykhan/video/6...
1199  https://www.tiktok.com/@thejohnnydshow/video/6...

[1200 rows x 52 columns]>

In [6]:
df.describe()

,authorMeta/digg,authorMeta/fans,authorMeta/following,authorMeta/heart,authorMeta/id,authorMeta/video,commentCount,createTime,diggCount,effectStickers/0/ID,...,effectStickers/1/ID,effectStickers/1/stickerStats/useCount,hashtags/0/id,hashtags/1/id,id,playCount,shareCount,videoMeta/duration,videoMeta/height,videoMeta/width
count,1.200000e+03,1.200000e+03,1200.000000,1.200000e+03,1.200000e+03,1200.000000,1200.000000,1.200000e+03,1.200000e+03,8.000000e+01,...,1.600000e+01,5.0,1.198000e+03,1.181000e+03,1.200000e+03,1.200000e+03,1.200000e+03,1200.000000,1200.000000,1200.000000
mean,1.894140e+04,7.124049e+06,508.820000,1.475789e+08,5.912425e+18,618.774167,53554.415000,1.621667e+09,6.577728e+06,4.966965e+05,...,4.777991e+05,0.0,2.975124e+16,2.407725e+16,6.965008e+18,5.468718e+07,1.569660e+05,29.741667,999.881667,582.128333
std,1.660581e+05,2.096570e+07,1237.753254,3.599765e+08,2.265439e+18,1598.081980,74139.653978,2.622762e+07,5.867806e+06,2.934072e+05,...,3.409627e+05,0.0,4.555694e+17,4.089334e+17,1.126466e+17,5.784957e+07,2.546967e+05,28.546173,124.434666,69.854992
min,0.000000e+00,4.180000e+02,0.000000,6.064000e+03,1.003043e+06,1.000000,0.000000,1.526468e+09,9.670000e+02,2.295440e+05,...,5.058800e+04,0.0,5.690000e+02,6.050000e+02,6.556132e+18,9.225000e+03,0.000000e+00,0.000000,0.000000,0.000000
25%,1.044250e+03,2.792000e+05,38.000000,8.200000e+06,6.621075e+18,113.000000,8459.000000,1.605963e+09,1.900000e+06,2.638400e+05,...,3.194450e+05,0.0,1.812100e+04,1.636200e+04,6.897559e+18,1.447500e+07,1.717500e+04,13.000000,1024.000000,576.000000
50%,4.908000e+03,1.300000e+06,131.000000,2.620000e+07,6.768211e+18,315.500000,29500.000000,1.623795e+09,5.700000e+06,4.547470e+05,...,3.910490e+05,0.0,1.633230e+05,1.331060e+05,6.974147e+18,3.690000e+07,6.515000e+04,19.000000,1024.000000,576.000000
75%,1.550000e+04,4.525000e+06,403.250000,1.074000e+08,6.864622e+18,754.000000,70500.000000,1.644295e+09,9.025000e+06,4.595610e+05,...,4.547740e+05,0.0,1.396414e+07,2.042264e+07,7.062194e+18,7.085000e+07,1.971750e+05,41.000000,1024.000000,576.000000
max,5.700000e+06,1.475000e+08,10000.000000,2.300000e+09,7.117986e+18,34500.000000,715500.000000,1.658732e+09,3.720000e+07,1.574533e+06,...,1.472630e+06,0.0,7.120048e+18,7.045407e+18,7.124201e+18,3.548000e+08,2.800000e+06,356.000000,1280.000000,1080.000000

In [7]:
df.columns

Index(['authorMeta/avatar', 'authorMeta/digg', 'authorMeta/fans',
       'authorMeta/following', 'authorMeta/heart', 'authorMeta/id',
       'authorMeta/name', 'authorMeta/nickName', 'authorMeta/signature',
       'authorMeta/verified', 'authorMeta/video', 'commentCount', 'createTime',
       'createTimeISO', 'diggCount', 'downloaded', 'effectStickers/0/ID',
       'effectStickers/0/name', 'effectStickers/0/stickerStats/useCount',
       'effectStickers/1/ID', 'effectStickers/1/name',
       'effectStickers/1/stickerStats/useCount', 'hashtags/0/cover',
       'hashtags/0/id', 'hashtags/0/name', 'hashtags/0/title',
       'hashtags/1/cover', 'hashtags/1/id', 'hashtags/1/name',
       'hashtags/1/title', 'id', 'mediaUrls/0', 'mentions/0', 'mentions/1',
       'mentions/2', 'mentions/3', 'mentions/4', 'mentions/5',
       'musicMeta/musicAlbum', 'musicMeta/musicAuthor', 'musicMeta/musicName',
       'musicMeta/musicOriginal', 'musicMeta/playUrl', 'playCount',
       'searchHashtag/name', 'searchHashtag/views', 'shareCount', 'text',
       'videoMeta/duration', 'videoMeta/height', 'videoMeta/width',
       'webVideoUrl'],
      dtype='object')

In [8]:
df.shape

(1200, 52)

### 2. Splitting Dataset into Pairs (Miraya) <a class="anchor" id="sec2"></a>

### 3. Jyontika's Section: Author and Video Meta Data? <a class="anchor" id="sec3"></a>

In [5]:
## creating pairs from the dataset to simulate?

### 4. Miraya's Section: Music <a class="anchor" id="sec4"></a>

### 5. Audrey's Section: Hashtags <a class="anchor" id="sec5"></a>

In [3]:
# test data from group 2
df_test = pd.read_csv('02-08-19-22_like_by_random_data_liked_videos copy.csv')
df_test

,batch,index,music,hashtag,author,likes,comments,shares,saves
0,1,0,All Night - Ndup,"fyp, foryou, foryoupage, xybca, xyzabc, viral,...",dexinlive,366300,6277,48100,22200
1,1,3,original sound - billiesxfuture,"billieeilish, fyp, vsp, velocity, xyzbca, bill...",billiesxfuture,118000,711,28400,544
2,1,4,original sound - Love ♥ BankrollDyl💸,"fyp, bankrolldyl, funyyvideos, beautiful",i.tsbankrolldyl,1963,13,352,15
3,1,5,original sound - Goldenfilmz🎞🌼,siblings,_milkymuffin_,698500,1676,29300,1903
4,1,7,original sound - LYRICS VILLA,NaN,..hannah13,46800,870,1818,77
...,...,...,...,...,...,...,...,...,...
64,5,20,original sound - itsloveee33,"foryourpage, theprincefamily, fyp, bianncaprince",itsloveee33,10800,40,1038,24
65,5,21,original sound - 𝐀𝐈𝐒𝐇𝐀 𝐏𝐀𝐋𝐌𝐄𝐑❦,"getreadywithme, grwm, grwmvideo, relatable, vi...",aaggrwm,100500,687,5473,169
66,5,22,Lemme get that - Frizz🗽.,@elibailar,zah1de_kyc,51000,71,3669,155
67,5,23,original sound - spo6kzie,"fyp, viral, trending, highschool, relatable, j...",courtenaymitchel,290100,2647,35000,2752
68,5,26,original sound - ✰,"fyp, fashion, fun, dance",dlxstv,45200,305,6499,271

In [4]:
df_test1 = df_test[["batch", "index", "hashtag"]].copy()
df_test1

    batch  index                                            hashtag
0       1      0  fyp, foryou, foryoupage, xybca, xyzabc, viral,...
1       1      3  billieeilish, fyp, vsp, velocity, xyzbca, bill...
2       1      4           fyp, bankrolldyl, funyyvideos, beautiful
3       1      5                                           siblings
4       1      7                                                NaN
..    ...    ...                                                ...
64      5     20   foryourpage, theprincefamily, fyp, bianncaprince
65      5     21  getreadywithme, grwm, grwmvideo, relatable, vi...
66      5     22                                         @elibailar
67      5     23  fyp, viral, trending, highschool, relatable, j...
68      5     26                           fyp, fashion, fun, dance

[69 rows x 3 columns]

In [5]:
# see what hashtags look like
print(list(df_test["hashtag"]))

['fyp, foryou, foryoupage, xybca, xyzabc, viral, trending, relatable, dexinlive', 'billieeilish, fyp, vsp, velocity, xyzbca, billiesxfuture, billieeilishedits, billie, blondiebillie', 'fyp, bankrolldyl, funyyvideos, beautiful', 'siblings', nan, 'fyp, zyxcba, foryou, relatable', 'offendingeverybody, animated, fyp', 'fyp, viral, trending, relateable', nan, 'billieeilish, billieeilishedit, aezpbills, fyp, foryou', nan, 'fyp, viral, tiktok, funny, jokes, bestfriend, conversation, random, annoying, relatable, brockton, massachusetts, brocktonhighschool', 'fyp, fyp, Love, A, blowup%3F, blowthisup', nan, 'familymatters, 90stvshows, 90sthrowback, showclips, foryoupage, fyp', 'fyp, basketball, hooper, relatable, viral, whoisjadenn', 'jesserejame, tmcjesse', '@barstooloutdoors, @bethanywiggins8', 'fyp, tiktok, greenscreenvideo', 'foryoupage, fyp, 2024, blowup, newbeginning, viral, nyanditmalual', 'fyp, bankrolldyl, funyyvideos, beautiful', 'fy, fyp, meme, funnyvideos%F0%9F%98%82, randommeme, memerandom, memevideo, videomeme, funnytiktok, tiktokmeme, memetiktok, school, schoollife, schoolmeme, schoolmemories, schoolhacks, schoolmemes%F0%9F%98%82, funnyschool, funnyschoolmoment, funnyschoolstories', 'billie, eilish, billieedit, billieeilishedit, goldwinqs, vsp, vspedit, capcut, capcutedit, edit, editaudio, billieeilish, concert, performance, velocity, velocityedit, billieeilishblondehair, hipslipsassandacartier, hellomf, @overbills, @billieeilishhome, @billieeilish', nan, 'billieeilish, billieeilishedit, billieeilishgrammys, wwafawdwg, greenroots, foryoupage, fyp%E3%82%B7, xybca, kouprmytroupr', '@meganmichele__, foryou, gaming, funny, skit', '4kt%F0%9F%92%9A, nba, neverbrokeagain, yb, 38baby', 'pov, @ariete_asmr, asmr, asmrtriggers, asmrsounds, emojichallenge, foryou, fy, fyp', nan, nan, 'cyruskaep, billieeilishedits, billieeilish, aftereffects, fyp, aftereffects', '@w4ybright, billieeilish, fyp, piettraeditss2, billieeilish, viral, aeedit, billieeilishedit', 'fyp%E3%82%B7, foryou, zyxcba, jahseh, jasehonfroy, xxxtentacion%F0%9F%92%94%F0%9F%92%94%F0%9F%92%94%F0%9F%92%94%F0%9F%92%94%F0%9F%98%AD%F0%9F%98%AD%F0%9F%98%AD%F0%9F%98%AD%F0%9F%98%AD%F0%9F%98%AD', 'tvshow, foryou, movieclips, amadeafamliyfuneral, fyp, film, amadeamliyfunreal', nan, 'initial, trend, love, amour, couple, a, a, crush, neige', 'fyp', 'school, fyp', 'hoodchristmascarols, christmas, delulu, justagirl, coquette', 'masc, wlw, lgbtq', 'itscitygirljiya, talkswithme', 'fyp, melaniemartinez, dancer', '@liv.kap, anesthesia, funny, goviral, foryou, high', 'eminem, hairstyle, haircut', 'dabzy_editzzz, fyp, edit, fyyyyyyyyyyyyyyyy, foryourpage', 'chainsfr, animated, fyp', nan, 'family, netflix, movie, wyatt', 'fyp, viral, 612boys', 'dukedennis, rizz, amp, millave, arizona, fruitful', nan, 'chainsfr, animated, schoolfight, fight, foru, viral', 'fyp, viral, dmv', 'fyp, pourtoi', '@donny_teee, gloveryawn, thevillain', 'fyp, fashion, fun, dance', nan, 'skyzooprod, fup, on, weeknd, fortnite, edit, recommendations', 'fyp, school', 'fyp, fashion, dance', nan, 'handshake', 'keyboard, amazonfind, trend, fyp, initals, buyit, linkinbio, viral', 'foryou, foryoupage, fyp%E3%82%B7, viral, blowthisup, trending, brohns01, xyzbca, fyp', 'foryourpage, theprincefamily, fyp, bianncaprince', 'getreadywithme, grwm, grwmvideo, relatable, viralvideo, britishhumour', '@elibailar', 'fyp, viral, trending, highschool, relatable, jokes, fyp%E3%82%B7%E3%82%9Aviral, 41, jujuwalk', 'fyp, fashion, fun, dance']

In [7]:
def process_hashtags(hashtag_str):
    if type(hashtag_str) == str:
        return hashtag_str.split(', ')
    else:
        return float("NaN")

#process_hashtags = lambda x: x.split(", ")

process_hashtags("fyp, bankrolldyl, funyyvideos, beautiful")

['fyp', 'bankrolldyl', 'funyyvideos', 'beautiful']

In [8]:
df_test1["hashtag"] = df_test["hashtag"].apply(process_hashtags)
df_test1 = df_test1.explode("hashtag")

In [9]:
df_test1

    batch  index     hashtag
0       1      0         fyp
0       1      0      foryou
0       1      0  foryoupage
0       1      0       xybca
0       1      0      xyzabc
..    ...    ...         ...
67      5     23    jujuwalk
68      5     26         fyp
68      5     26     fashion
68      5     26         fun
68      5     26       dance

[324 rows x 3 columns]

In [10]:
# remove % from parsed hashtags (assume that anything after the % was not meant to be scraped)
filtered_percent = df_test1['hashtag'].notna() & df_test1['hashtag'].str.contains('%')
df_test1.loc[filtered_percent, 'hashtag'] = df_test1.loc[filtered_percent, 'hashtag'].str.split('%').str[0]


# separate out tagged accounts
filtered_at = df_test1['hashtag'].notna() & df_test1['hashtag'].str.contains('@')
df_tagged = df_test1[filtered_at]
df_test1.drop(df_test1.index[filtered_at], inplace=True)

df_test1

    batch  index     hashtag
0       1      0         fyp
0       1      0      foryou
0       1      0  foryoupage
0       1      0       xybca
0       1      0      xyzabc
..    ...    ...         ...
67      5     23    jujuwalk
68      5     26         fyp
68      5     26     fashion
68      5     26         fun
68      5     26       dance

[268 rows x 3 columns]

In [11]:
df_tagged.rename(columns={'hashtag': 'tagged'}, inplace=True) 
# what do we want to do with this? how to handle nan?

df_tagged

/var/folders/ny/5mz_1h8j5c31x__pd0t4xhxw0000gn/T/ipykernel_30064/1413259590.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tagged.rename(columns={'hashtag': 'tagged'}, inplace=True)

    batch  index             tagged
17      2     20  @barstooloutdoors
17      2     20   @bethanywiggins8
22      3      4         @overbills
22      3      4  @billieeilishhome
22      3      4      @billieeilish
25      3     10    @meganmichele__
27      3     12       @ariete_asmr
31      3     18         @w4ybright
42      4      4           @liv.kap
54      4     22        @donny_teee
66      5     22         @elibailar

In [12]:
hashtags_list = list(df_test1["hashtag"])
print(hashtags_list)

['fyp', 'foryou', 'foryoupage', 'xybca', 'xyzabc', 'viral', 'trending', 'relatable', 'dexinlive', 'billieeilish', 'fyp', 'vsp', 'velocity', 'xyzbca', 'billiesxfuture', 'billieeilishedits', 'billie', 'blondiebillie', 'fyp', 'bankrolldyl', 'funyyvideos', 'beautiful', 'siblings', nan, 'fyp', 'zyxcba', 'foryou', 'relatable', 'offendingeverybody', 'animated', 'fyp', 'fyp', 'viral', 'trending', 'relateable', nan, 'billieeilish', 'billieeilishedit', 'aezpbills', 'fyp', 'foryou', nan, 'fyp', 'viral', 'tiktok', 'funny', 'jokes', 'bestfriend', 'conversation', 'random', 'annoying', 'relatable', 'brockton', 'massachusetts', 'brocktonhighschool', 'fyp', 'fyp', 'Love', 'A', 'blowup', 'blowthisup', nan, 'familymatters', '90stvshows', '90sthrowback', 'showclips', 'foryoupage', 'fyp', 'fyp', 'basketball', 'hooper', 'relatable', 'viral', 'whoisjadenn', 'jesserejame', 'tmcjesse', 'fyp', 'tiktok', 'greenscreenvideo', 'foryoupage', 'fyp', '2024', 'blowup', 'newbeginning', 'viral', 'nyanditmalual', 'fyp', 'bankrolldyl', 'funyyvideos', 'beautiful', 'fy', 'fyp', 'meme', 'funnyvideos', 'randommeme', 'memerandom', 'memevideo', 'videomeme', 'funnytiktok', 'tiktokmeme', 'memetiktok', 'school', 'schoollife', 'schoolmeme', 'schoolmemories', 'schoolhacks', 'schoolmemes', 'funnyschool', 'funnyschoolmoment', 'funnyschoolstories', nan, 'billieeilish', 'billieeilishedit', 'billieeilishgrammys', 'wwafawdwg', 'greenroots', 'foryoupage', 'fyp', 'xybca', 'kouprmytroupr', '4kt', 'nba', 'neverbrokeagain', 'yb', '38baby', nan, nan, 'cyruskaep', 'billieeilishedits', 'billieeilish', 'aftereffects', 'fyp', 'aftereffects', 'fyp', 'foryou', 'zyxcba', 'jahseh', 'jasehonfroy', 'xxxtentacion', 'tvshow', 'foryou', 'movieclips', 'amadeafamliyfuneral', 'fyp', 'film', 'amadeamliyfunreal', nan, 'initial', 'trend', 'love', 'amour', 'couple', 'a', 'a', 'crush', 'neige', 'fyp', 'school', 'fyp', 'hoodchristmascarols', 'christmas', 'delulu', 'justagirl', 'coquette', 'masc', 'wlw', 'lgbtq', 'itscitygirljiya', 'talkswithme', 'fyp', 'melaniemartinez', 'dancer', 'eminem', 'hairstyle', 'haircut', 'dabzy_editzzz', 'fyp', 'edit', 'fyyyyyyyyyyyyyyyy', 'foryourpage', 'chainsfr', 'animated', 'fyp', nan, 'family', 'netflix', 'movie', 'wyatt', 'fyp', 'viral', '612boys', 'dukedennis', 'rizz', 'amp', 'millave', 'arizona', 'fruitful', nan, 'chainsfr', 'animated', 'schoolfight', 'fight', 'foru', 'viral', 'fyp', 'viral', 'dmv', 'fyp', 'pourtoi', 'fyp', 'fashion', 'fun', 'dance', nan, 'skyzooprod', 'fup', 'on', 'weeknd', 'fortnite', 'edit', 'recommendations', 'fyp', 'school', 'fyp', 'fashion', 'dance', nan, 'handshake', 'keyboard', 'amazonfind', 'trend', 'fyp', 'initals', 'buyit', 'linkinbio', 'viral', 'foryou', 'foryoupage', 'fyp', 'viral', 'blowthisup', 'trending', 'brohns01', 'xyzbca', 'fyp', 'foryourpage', 'theprincefamily', 'fyp', 'bianncaprince', 'getreadywithme', 'grwm', 'grwmvideo', 'relatable', 'viralvideo', 'britishhumour', 'fyp', 'viral', 'trending', 'highschool', 'relatable', 'jokes', 'fyp', '41', 'jujuwalk', 'fyp', 'fashion', 'fun', 'dance']

In [13]:
## recombine
df_test2 = (df_test1.groupby(['batch', 'index'])
      .agg({'hashtag': lambda x: x.tolist()}).reset_index())

df_test2

    batch  index                                            hashtag
0       1      0  [fyp, foryou, foryoupage, xybca, xyzabc, viral...
1       1      3  [billieeilish, fyp, vsp, velocity, xyzbca, bil...
2       1      4         [fyp, bankrolldyl, funyyvideos, beautiful]
3       1      5                                         [siblings]
4       1      7                                              [nan]
..    ...    ...                                                ...
56      5     17  [foryou, foryoupage, fyp, viral, blowthisup, t...
57      5     20  [foryourpage, theprincefamily, fyp, bianncapri...
58      5     21  [getreadywithme, grwm, grwmvideo, relatable, v...
59      5     23  [fyp, viral, trending, highschool, relatable, ...
60      5     26                         [fyp, fashion, fun, dance]

[61 rows x 3 columns]

In [95]:
batch_hashtags = df_test1["hashtag"].groupby(df_test1["batch"])
batch_hashtags.count()

batch
1    27
2    79
3    53
4    40
5    57
Name: hashtag, dtype: int64

In [15]:
hashtag_list = list(df_test2['hashtag'])
hashtag_list

[['fyp',
  'foryou',
  'foryoupage',
  'xybca',
  'xyzabc',
  'viral',
  'trending',
  'relatable',
  'dexinlive'],
 ['billieeilish',
  'fyp',
  'vsp',
  'velocity',
  'xyzbca',
  'billiesxfuture',
  'billieeilishedits',
  'billie',
  'blondiebillie'],
 ['fyp', 'bankrolldyl', 'funyyvideos', 'beautiful'],
 ['siblings'],
 [nan],
 ['fyp', 'zyxcba', 'foryou', 'relatable'],
 ['offendingeverybody', 'animated', 'fyp'],
 ['fyp', 'viral', 'trending', 'relateable'],
 [nan],
 ['billieeilish', 'billieeilishedit', 'aezpbills', 'fyp', 'foryou'],
 [nan],
 ['fyp',
  'viral',
  'tiktok',
  'funny',
  'jokes',
  'bestfriend',
  'conversation',
  'random',
  'annoying',
  'relatable',
  'brockton',
  'massachusetts',
  'brocktonhighschool'],
 ['fyp', 'fyp', 'Love', 'A', 'blowup', 'blowthisup'],
 [nan],
 ['familymatters',
  '90stvshows',
  '90sthrowback',
  'showclips',
  'foryoupage',
  'fyp'],
 ['fyp', 'basketball', 'hooper', 'relatable', 'viral', 'whoisjadenn'],
 ['jesserejame', 'tmcjesse'],
 ['fyp', 'tiktok', 'greenscreenvideo'],
 ['foryoupage',
  'fyp',
  '2024',
  'blowup',
  'newbeginning',
  'viral',
  'nyanditmalual'],
 ['fyp', 'bankrolldyl', 'funyyvideos', 'beautiful'],
 ['fy',
  'fyp',
  'meme',
  'funnyvideos',
  'randommeme',
  'memerandom',
  'memevideo',
  'videomeme',
  'funnytiktok',
  'tiktokmeme',
  'memetiktok',
  'school',
  'schoollife',
  'schoolmeme',
  'schoolmemories',
  'schoolhacks',
  'schoolmemes',
  'funnyschool',
  'funnyschoolmoment',
  'funnyschoolstories'],
 [nan],
 ['billieeilish',
  'billieeilishedit',
  'billieeilishgrammys',
  'wwafawdwg',
  'greenroots',
  'foryoupage',
  'fyp',
  'xybca',
  'kouprmytroupr'],
 ['4kt', 'nba', 'neverbrokeagain', 'yb', '38baby'],
 [nan],
 [nan],
 ['cyruskaep',
  'billieeilishedits',
  'billieeilish',
  'aftereffects',
  'fyp',
  'aftereffects'],
 ['fyp', 'foryou', 'zyxcba', 'jahseh', 'jasehonfroy', 'xxxtentacion'],
 ['tvshow',
  'foryou',
  'movieclips',
  'amadeafamliyfuneral',
  'fyp',
  'film',
  'amadeamliyfunreal'],
 [nan],
 ['initial', 'trend', 'love', 'amour', 'couple', 'a', 'a', 'crush', 'neige'],
 ['fyp'],
 ['school', 'fyp'],
 ['hoodchristmascarols', 'christmas', 'delulu', 'justagirl', 'coquette'],
 ['masc', 'wlw', 'lgbtq'],
 ['itscitygirljiya', 'talkswithme'],
 ['fyp', 'melaniemartinez', 'dancer'],
 ['eminem', 'hairstyle', 'haircut'],
 ['dabzy_editzzz', 'fyp', 'edit', 'fyyyyyyyyyyyyyyyy', 'foryourpage'],
 ['chainsfr', 'animated', 'fyp'],
 [nan],
 ['family', 'netflix', 'movie', 'wyatt'],
 ['fyp', 'viral', '612boys'],
 ['dukedennis', 'rizz', 'amp', 'millave', 'arizona', 'fruitful'],
 [nan],
 ['chainsfr', 'animated', 'schoolfight', 'fight', 'foru', 'viral'],
 ['fyp', 'viral', 'dmv'],
 ['fyp', 'pourtoi'],
 ['fyp', 'fashion', 'fun', 'dance'],
 [nan],
 ['skyzooprod', 'fup', 'on', 'weeknd', 'fortnite', 'edit', 'recommendations'],
 ['fyp', 'school'],
 ['fyp', 'fashion', 'dance'],
 [nan],
 ['handshake'],
 ['keyboard',
  'amazonfind',
  'trend',
  'fyp',
  'initals',
  'buyit',
  'linkinbio',
  'viral'],
 ['foryou',
  'foryoupage',
  'fyp',
  'viral',
  'blowthisup',
  'trending',
  'brohns01',
  'xyzbca',
  'fyp'],
 ['foryourpage', 'theprincefamily', 'fyp', 'bianncaprince'],
 ['getreadywithme',
  'grwm',
  'grwmvideo',
  'relatable',
  'viralvideo',
  'britishhumour'],
 ['fyp',
  'viral',
  'trending',
  'highschool',
  'relatable',
  'jokes',
  'fyp',
  '41',
  'jujuwalk'],
 ['fyp', 'fashion', 'fun', 'dance']]

In [16]:
from gensim.models import Word2Vec

In [20]:
## try using word2vec skipgram model
# https://www.tensorflow.org/text/tutorials/word2vec

model = Word2Vec(sentences=hashtag_list, vector_size=100, window=5, min_count=1, sg=1)

In [29]:
def get_similarity(hashtag1, hashtag2):
    try:
        similarity = model.wv.similarity(hashtag1, hashtag2)
        return similarity
    except KeyError:
        print("Error: either hashtag not found in model")
        return None 

# Example usage
hashtag1 = 'billieeilish'
hashtag2 = 'billie'
similarity_score = get_similarity(hashtag1, hashtag2)
print(f"Similarity between '{hashtag1}' and '{hashtag2}': {similarity_score}")

Similarity between 'billieeilish' and 'billie': 0.0016515761381015182